const path = '/icons'

export default {
	ACARA_ICON: `${path}/acara-icon.png`,
	ACARA_ACTIVE_ICON: `${path}/acara-active-icon.png`,
	BISMILLAH_ICON: `${path}/bismillah-icon.png`,
	BISMILLAH_BLACK_ICON: `${path}/bismillah-black-icon.png`,
	DISTANCE_ICON: `${path}/distance-icon.png`,
	GALERI_ICON: `${path}/galeri-icon.png`,
	GALERI_ACTIVE_ICON: `${path}/galeri-active-icon.png`,
	HAND_WASHING_ICON: `${path}/hand-washing-icon.png`,
	HEAT_ICON: `${path}/heat-icon.png`,
	MASK_ICON: `${path}/mask-icon.png`,
	MEMPELAI_ICON: `${path}/mempelai-icon.png`,
	MEMPELAI_ACTIVE_ICON: `${path}/mempelai-active-icon.png`,
	PENERIMA_ICON: `${path}/penerima-icon.png`,
	PENERIMA_ACTIVE_ICON: `${path}/penerima-active-icon.png`,
	PENUTUP_ICON: `${path}/penutup-icon.png`,
	PENUTUP_ACTIVE_ICON: `${path}/penutup-active-icon.png`,
	PETA_ICON: `${path}/peta-icon.png`,
	PETA_ACTIVE_ICON: `${path}/peta-active-icon.png`,
	PROTOKOL_ICON: `${path}/protokol-icon.png`,
	PROTOKOL_ACTIVE_ICON: `${path}/protokol-active-icon.png`,
	SAMPUL_ICON: `${path}/sampul-icon.png`,
	SAMPUL_ACTIVE_ICON: `${path}/sampul-active-icon.png`,
}
